version: "3"

services:

  configuration-sdk-csharp-preview-build:
    build: .
    container_name: configuration-sdk-csharp-preview-build
    image: finbourne/configuration-sdk-csharp-preview-build
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_CONFIGURATION_API_URL
      - FBN_APP_NAME
    volumes:
      - .:/usr/src